# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Config": "00_core.ipynb",
         "URLs": "00_core.ipynb",
         "download_url": "00_core.ipynb",
         "download_data": "00_core.ipynb",
         "file_extract": "00_core.ipynb",
         "untar_data": "00_core.ipynb",
         "make_df": "00_core.ipynb",
         "list_teams": "00_core.ipynb",
         "list_game_ids": "00_core.ipynb",
         "Y_MODIFIER": "00_core.ipynb",
         "X_MODIFIER": "00_core.ipynb",
         "plot_team": "00_core.ipynb",
         "plot_winner": "00_core.ipynb",
         "plot_loser": "00_core.ipynb",
         "list_team_players": "00_core.ipynb",
         "plot_player": "00_core.ipynb",
         "least_effective_shot_team": "00_core.ipynb",
         "least_effective_shot_league": "00_core.ipynb",
         "most_effective_shot_league": "00_core.ipynb",
         "least_effective_shot_player": "00_core.ipynb",
         "most_effective_shot_player": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://theccalderon.github.io/shot_chart/"

git_url = "https://github.com/theccalderon/shot_chart/tree/master/"

def custom_doc_links(name): return None
