# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Config": "00_core.ipynb",
         "URLs": "00_core.ipynb",
         "download_url": "00_core.ipynb",
         "download_data": "00_core.ipynb",
         "file_extract": "00_core.ipynb",
         "untar_data": "00_core.ipynb",
         "make_df": "00_core.ipynb",
         "delegates": "00_core.ipynb",
         "Shots": "00_core.ipynb",
         "list_teams": "00_core.ipynb",
         "list_game_ids": "00_core.ipynb",
         "TeamShots": "00_core.ipynb",
         "list_team_players": "00_core.ipynb",
         "PlayerShots": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://theccalderon.github.io/shot_chart/"

git_url = "https://github.com/theccalderon/shot_chart/tree/master/"

def custom_doc_links(name): return None
